apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gamedivers
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s
  prune: true
  wait: true
  timeout: 5m
  targetNamespace: gamedivers
  serviceAccountName: gamedivers-reconciler
  sourceRef:
    kind: GitRepository
    name: gamedivers-repo
