apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gamedivers
  namespace: flux-system
spec:
  interval: 1m
  path: ../../k8s
  prune: true
  timeout: 5m
  wait: false
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: go-api
      namespace: gamedivers
    - apiVersion: apps/v1
      kind: Deployment
      name: web
      namespace: gamedivers

  targetNamespace: gamedivers
  serviceAccountName: gamedivers-reconciler
  sourceRef:
    kind: GitRepository
    name: gamedivers-repo

  decryption:
  provider: sops
  secretRef:
    name: sops-age
