apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamedivers-api
spec:
  ingressClassName: traefik
  rules:
    - host: gamedivers.de
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gamedivers-api
                port:
                  number: 80
