apiVersion: v1
kind: Secret
metadata:
    name: go-api-env-secrets
type: Opaque
stringData:
    ISTHEREANYDEAL_API_KEY: ENC[AES256_GCM,data:ZncFA8E2GOyZE5lX3so2rGgIIWjVk4i4eLnZWiiU9Bu2fhowKJ6+DA==,iv:vyscOuAEvznj3Ox4nQMPHC8+2ecwPb3KM8m1rNbaYzs=,tag:ullKLWpOX7cfWGVPHqR7Fg==,type:str]
    KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:9vd1eSfhRXPNf0p8Z9A=,iv:kPxuicqy1LLMVWfOK4t9FMb0OBoslln1hjFX+6n5DCQ=,tag:Ssu/B5Ay44bXmnN24lk7tQ==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:WPZk6ORXT4XizCSmg1Gt5R4zGXcBXAEBN8lG0xXVia8=,iv:5+HBFYoplryj0rs52ESnJzd65jxvX+3ww51f94X/AGM=,tag:U+C8Tvumhhcf6VT2axpVPA==,type:str]
    STEAM_API_KEY: ENC[AES256_GCM,data:USj9PaRe3OUhOG0SZwvfuNm850l4DsqjSHdfkVC2jRA=,iv:EhhB0d+IEunrzindXw9TPEu+bnGna2C4BZSHlMEb0Do=,tag:ha5NNcRwid6TKba2yHD9tQ==,type:str]
    EPIC_CLIENT_ID: ENC[AES256_GCM,data:v7ApBY1odVfqWCPAbUjqg12CjwYldr7Dm1wml3d37XY=,iv:HXl/rJOcnm+a5Qd3RiYmjnsO2BkNseQXUZGOMXGH6Ac=,tag:2gVH1/jKNrFOmgEl53DrLQ==,type:str]
    EPIC_CLIENT_SECRET: ENC[AES256_GCM,data:BPW5gRmjjmgBs6o4QXlNhu/gf8p2ez65wr5yb2Eyffn16hDxHYYUTPsJXA==,iv:iN6ZIjCQ2KRqr4KiLYi5F4kkbTYRSF5hAZfQNCWTZFs=,tag:v6SlOfHN3g4Mb84WKhOoEw==,type:str]
sops:
    age:
        - recipient: age17j86p3pj260t0g03xv5wsq6u8y422m634pd5j4tdv92z0hf2hc4s4gyt6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTFc2QlZERXlJTEdER2NJ
            SDNKVVRwWjVqR0ZEdU5wM2Y5VEJ2YW0ybFVBCkNoR2pRMTBXczZLTmJOT3NUbWZG
            WWt4bUw2UTJWd0VXanB5MnBKdHVmRHMKLS0tIHFTQ3JaY2haYVkrck1CUnBRdnBP
            UVI4ZUFUU0dnZ3VneUliT0xkV29JdkUK/Xu6iAj7Y/M8SipCASwFpQy/G/W84C6r
            yUodx04ooKRH9yX8x24g9YdD6/IPudM/8+ECEktoxM2uXYLkfPccMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T23:04:32Z"
    mac: ENC[AES256_GCM,data:n07vW//cGVSoFMbTXyW8wzjQgJvxNNIFo5yMyfKb6E7rEvdfJHjL9QZKv9w+EukOmrmuNc9eV7dVB1b7g+QeXFq+TZYp+/owueb5N9FGLJLCqKauHP1srW3aeHICKhBXIFbEs6ZPqFXqW/bbGoeGlfrXPByuOuSg4N2pJMDhw7Y=,iv:aLtqzG7Zb4HLWGGWQ5KowewfY0W3HgGwTyc0RlqRbUw=,tag:UZVTY5n43jAJwV2CsvwwAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
