apiVersion: v1
kind: Secret
metadata:
    name: go-api-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:e3HenVMHRr7XDlPlWdbrvbm6TwdIFbhmpFWeFkkhMqAXQTDaf8hDvVsjJOeXDD7l2b9GYAd/HEf2F8mVC1SkPduTSG3BJdUM,iv:9wmcxEz0lk8ZufeAX/+rXcLdWkzvWZM2+iDTDkXdsbw=,tag:GetHPuQxl5sEMpsCEThrfw==,type:str]
sops:
    age:
        - recipient: age17j86p3pj260t0g03xv5wsq6u8y422m634pd5j4tdv92z0hf2hc4s4gyt6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRklVVWMyWWo0WUhkeW0x
            TUlCS1ZHVHdKZ2Qyb0hqVlNQamQ4dnpiN1dBCjZWK1JaRE9wQXRIcmNRV3BYd2ZY
            TS9tMUFzcm5qSno1cmlMOWcxT2RubzgKLS0tIER4T3FweENKaWhlMExWSTZNTHZ1
            WG5vc3IyV1l3SStWU2I5R3NCa1hJNlUKcIF3rYP4v5OfxoO+nQUAxhthJ8WlvVoi
            fF1F7TvzDGV0Ds9mrBkHpSrLVA+LEYYgUxBjLQDQhWaAU31xkwuIHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:18:21Z"
    mac: ENC[AES256_GCM,data:2B4agI4gDhtda65wATLVrpZR36oK4b5ewe90EbJiYJ60TR9A4QqedKHsaPDQGRkvYVuY48NY/w8B07J61fxShX/9uWdAXwXgUD2C1OWUBat2iqUXJi69ySbKAJFzT9HR3eDGJ5KPCWS2o+V7+nSfPuUv6zcLl6ep0KrTJ/0RLXc=,iv:CDUxk7qW1h3t8PcSMcvvlTIpvRVDM5KlnJFeN1oYyUU=,tag:xrHf9LVpcW4/j8LafXi2Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
