apiVersion: v1
kind: Secret
metadata:
    name: go-api-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:bbizYxojj30Y84JOdeOIL9N2SgB6ytWkjYTztnbCSA5UpLYOVvSvk+pia0nQuZUxOWvLdlBpzT0LGd7Dq2OWQX0Da2GBJOkxc0s2R/ddaji9GBk=,iv:oNmkvbhf8WncOT/U/v+vclf4RUSw55fCOn3/1rKcJok=,tag:s8uwS3pvHuhtsdcOm3RScg==,type:str]
sops:
    age:
        - recipient: age17j86p3pj260t0g03xv5wsq6u8y422m634pd5j4tdv92z0hf2hc4s4gyt6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRb0xFeDlYUjMzOUNmNTRN
            UWUzS1ZzZXlnQmZwejgrNEdTTXoyWW9KUGo4Cmtpc3dnc01WQ2Vlaml4N2tSVmJO
            WlhhTEt4WHZqZkJGMmI2QXBNbVBXN1EKLS0tIHhGaUJuZjlUOVduTkx3dlNSV1Rv
            K1cydm1taHk0Y2huaGsrMDluVUVJMlkKSUWp23SbefmRhcGkAZBuZunFjAQ+IB//
            PYG+YryNH1vv9eDz2MJKnRU+ZxL/sNBsMCTgcRH8JWNi69wKwRxf1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T17:27:01Z"
    mac: ENC[AES256_GCM,data:1go9QJI0qMCmg6v60H6bOf/e7BsSk73U+zWATVVWf92Ozrq5swoVKeoY953H2h8MsI11Bm68nthl2oNUyU1hX19QCwcpZtHdxIqqQqKkzHIWxpAJCF+ubDP4CyM617x59T5AbOGjFvS0lAM+gIZv/shY8pE6SxKZHM/imdU8iYs=,iv:CtNLgrjczIjvGkDlIyGSVhkioTsY197GiX8cLlqfGlw=,tag:zLaRxDXUEh4Q7xggxo3G2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
