apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gamedivers
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/configmap.yaml
  - api/secret.yaml
  - api/secret-env.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
  - web/secret.yaml
  - postgres/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - postgres/networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: aio
images:
  - name: ghcr.io/duneslim/gamedivers-api
    newName: ghcr.io/duneslim/gamedivers-api
    newTag: 267bd294bb0e8c80af38542b353b4412ac12dc7c
  - name: ghcr.io/duneslim/gamedivers-website
    newName: ghcr.io/duneslim/gamedivers-website
    newTag: 267bd294bb0e8c80af38542b353b4412ac12dc7c
