apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gamedivers
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: aio
images:
  - name: ghcr.io/duneslim/aio-go-api
    newName: ghcr.io/duneslim/aio-go-api
    newTag: latest
  - name: ghcr.io/duneslim/aio-web
    newName: ghcr.io/duneslim/aio-web
    newTag: latest
