apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gamedivers
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: aio
images:
  - name: ghcr.io/duneslim/gamedivers-api
    newName: ghcr.io/duneslim/gamedivers-api
    newTag: 986dc85b09a5ec3f4b766b1653b44f558f682858
  - name: ghcr.io/duneslim/gamedivers-website
    newName: ghcr.io/duneslim/gamedivers-website
    newTag: 986dc85b09a5ec3f4b766b1653b44f558f682858
