apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-api

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml    # or service-lb.yaml
  - ingress.yaml
  - secret-auth.yaml

commonLabels:
  app: go-api

images:
  - name: ghcr.io/AIO/go-api
    newName: ghcr.io/AIO/go-api
    newTag: latest
