apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gamedivers
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/secret.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
  - postgres/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - postgres/networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: aio
images:
  - name: ghcr.io/duneslim/gamedivers-api
    newName: ghcr.io/duneslim/gamedivers-api
    newTag: 7815e23e47106b04c6e8dd23d21a5ea10d24ed60
  - name: ghcr.io/duneslim/gamedivers-website
    newName: ghcr.io/duneslim/gamedivers-website
    newTag: 7815e23e47106b04c6e8dd23d21a5ea10d24ed60
