apiVersion: v1
kind: Secret
metadata:
  name: go-api-auth
  namespace: go-api
type: Opaque
data:
  JWT_SECRET: "<base64-secret>"            
  ENCRYPTION_KEY: "<base64-32bytes>"       
  BNET_CLIENT_ID: "<base64-client-id>"
  BNET_CLIENT_SECRET: "<base64-client-secret>"
  BASE_URL: "<base64-backend-url>"    
