# service-lb.yaml
apiVersion: v1
kind: Service
metadata:
  name: go-api
  namespace: go-api
spec:
  type: LoadBalancer
  selector:
    app: go-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
