apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamedivers-website
  namespace: gamedivers
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-gamedivers
spec:
  ingressClassName: traefik
  tls:
    - hosts: [gamedivers.de]
      secretName: letsencrypt-gamedivers-account-key
  rules:
    - host: gamedivers.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gamedivers-website
                port:
                  number: 80
