apiVersion: v1
kind: Secret
metadata:
    name: gamedivers-website-secrets
type: Opaque
stringData:
    VITE_API_BASE: ENC[AES256_GCM,data:Ud/YAOXH8ynTf1yoXPkuebaAEUCY,iv:ltWGA1gVnzj8oYOB4JavYLrLXWykqJtZ8pDvfdOqdpI=,tag:K35oofpNpBrFRPanF2mxwQ==,type:str]
    VITE_ENABLE_CREDIT_CHEAT: ENC[AES256_GCM,data:K7Pcew==,iv:ob0R3tQpSawRchZiRHIdVutBC1VGmZC53WW0QBHXpr8=,tag:pOVryXix+roKimmdxuYI6g==,type:str]
sops:
    age:
        - recipient: age17j86p3pj260t0g03xv5wsq6u8y422m634pd5j4tdv92z0hf2hc4s4gyt6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUTF4NVAyNXYwTTN1OFRz
            bmZkSFB6NUwxLzNrb2IwcjZkN20rKzhMaWo4CnY2NTlqZy9sZ1p1NENEVTNRUFhw
            YUNudVJ0WDlJczRRYWRPelRIaW53WEUKLS0tIHdBQ09ZNGU0bWxiTkhwaTQyY2dB
            d3lKMks1NFVkS245eGNZSDJnL1hJUlEKch8/zf9CE802nf53SWp+CmXjp3YXGMM4
            S6ziR+67T5akV3hy/CGlZt074ytmzMRnXOccw3baewyHOjh1jDPxUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T19:39:24Z"
    mac: ENC[AES256_GCM,data:Q9LUAqzckw/bzmdJWzy0PgZzMaHD9MhGXjwWeqlsBZHbN5LsPqGVYJyp7cmjWlWHH4yv+iR6qP6Il6OcxHFNL2UHMOytQ4nX7Y67UPwUa6ClZhCQl9C92tWHLlOx6x2s5ggLjXJ18UBRhJJ/JRzz4vardtxh/++SxxfPU6tRf2E=,iv:FD1eknJcOwXCeNWNozffpfVcRje8svBteMgFCTLSP+4=,tag:CSzKaRcxEOgzYZi/Nc61FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
