apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 5m
  chart:
    spec:
      chart: zitadel
      version: ">=7.0.0 <8.0.0"
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: zitadel

  values:
    env:
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-zitadel-auth
            key: POSTGRES_PASSWORD
      - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-zitadel-auth
            key: POSTGRES_PASSWORD
      - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-smtp-secret
            key: SMTP_PASSWORD

    zitadel:
      masterkeySecretName: zitadel-masterkey

      configmapConfig:
        DefaultInstance:
          SMTPConfiguration:
            SMTP:
              Host: smtp.gmail.com:587
              User: dev.gamedivers@gmail.com
              Tls: true
            From: dev.gamedivers@gmail.com
            FromName: Gamedivers Auth
        ExternalDomain: auth.gamedivers.de
        ExternalSecure: true
        ExternalPort: 443
        TLS:
          Enabled: false 

        Database:
          Postgres:
            Host: postgres
            Port: 5432
            Database: zitadel
            User:
              Username: zitadel-user
              SSL:
                Mode: disable
            Admin:
              Username: zitadel-user
              SSL:
                Mode: disable
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-gamedivers"
      hosts:
        - host: auth.gamedivers.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: zitadel-tls
          hosts:
            - auth.gamedivers.de
    login:
      ingress:
        enabled: true
