apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zitadel
  namespace: zitadel
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-gamedivers
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth.gamedivers.de
      secretName: letsencrypt-gamedivers-auth
  rules:
    - host: auth.gamedivers.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zitadel
                port:
                  name: http
