apiVersion: v1
kind: Secret
metadata:
  name: postgres-zitadel-auth
  namespace: zitadel
type: Opaque
stringData:
  POSTGRES_USER: zitadel
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: zitadel
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
