apiVersion: v1
kind: Secret
metadata:
    name: postgres-zitadel-auth
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:8GZ9EYZxBYVtrA==,iv:OSREdrMjBf3P7lFXaPStCQ9gfjIxa7AUlz4G1yy9c1M=,tag:dTKM/wWgbmlcRh0ufAWj1w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:PPdjZy2msrClzE8q,iv:NHNb9JWxKyeRw6nbXBqXkPq9vqnm2YwVqrrahkOCdMU=,tag:lKkPs9+U0q+bDUhau9JL0Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:59nOvLiNOdZUNvco+hiJBvg3GwFdwX8KgQ==,iv:QzJyuL6cALCQQOS6seE4BRu8MYotZe3vwJT6jLdTLTM=,tag:hEqj9UOKChXa/s+UqMfXTQ==,type:str]
sops:
    age:
        - recipient: age17j86p3pj260t0g03xv5wsq6u8y422m634pd5j4tdv92z0hf2hc4s4gyt6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTDlhT0h0bkRnSHhqQ2hH
            aDJqdVVaQkdlVTBiZWMxWnZHRGVJb01FbDNFCjVZaW5LRkxUc2NlVFdvRnBnU2tz
            QXYwL0NWUDdQbG5RWTd6NTNpSCtHN3cKLS0tIGVIcERHRlB1UnIyL2xNbzh1eWp4
            OGpvZnpySStEZ1dZQ0gvV1YrTnU5dDgKAwqPLUgnZipXQL6qeTHmhFgfL312ZQpt
            Y8ClFSRrOxNA8j9rn6dp9NlLBeX05kfkFFNzVre1x/d0jddep/74Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T22:15:48Z"
    mac: ENC[AES256_GCM,data:vs6SSyeKHy2Q73v5GmRAql6S+/WLou7LVI14WdTEUGJtupIL96kA6LpZjma8O0F+nCNc8rn1Rve7R+6IOwqv+z36T3fhn79QD3waWkEAOamB8tjXp2TMkiCyH7LYd9DSL/DFfkdssz1rHpegMo3dN5pSttHsq3TqfFZXqQZEi98=,iv:orYQyHZ5dEacCoS0LlTcM+oSk0x+5fmMvjwUaTYdOBQ=,tag:BOXrA5HGXHTClcr43AoBWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
