apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:01KL0kPG9HeAAPcjmQ==,iv:oowEonUYNksNErPFG4ieUxPH2ue6l3DCO4+nKM4zXws=,tag:KjMjy1faTfWBlT2hLgB5Pg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hrxTL7pI19O9C9v5pL8x,iv:edcRfhZXCzBNCwd9Lh/cIYJChzjwPGCOOdPXonCpfWI=,tag:9MZZ+oSOzw9ffYJ/lyc18Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rouPHGd5FwJwLD/AJurx,iv:gal54hwh2+KqwLpuc4JxDldTIN2cCQbb5NG8AVCne1w=,tag:2fw9jehzMDW7RLyncc2jjQ==,type:str]
sops:
    age:
        - recipient: age17j86p3pj260t0g03xv5wsq6u8y422m634pd5j4tdv92z0hf2hc4s4gyt6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMENYbC8ySzBhcVFlRm1v
            UmZ5V0wxd2NUY0NSQmJRaEFnalFyK08vWGlVCkRUMVFPMlpPR1gvRGgydHRoTmh5
            S3BBNEtZSE8vei9vVUFGanJ4dk9mb2cKLS0tIG5oRVVHYnZjMmlEUGlHVzZFZmtU
            NkxLcGkyS2VUTUVNcTFTeWgrazJuUkkKN6jeoJldFOm9iiobJ8JNJLE1eTB0Hahu
            xIPQlYuiA3meRmz2+9FyttDG53ProjP96D08gw1nX276QC55jADfXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:18:29Z"
    mac: ENC[AES256_GCM,data:y7xYs5UR/tbo37nPUF9l6Fc5h886bUFOiN4co4r5f40NWjZT6sUTApzpknD69McTUEBPmtEgRr0htYk/JZ29N29zEh8jaG5bEOpL9cDVs+aE5qfqGUDHpm/Cx5JF7HY7PlBlVjAhp97AZNa3pAbDcnhxMq02L0/gxhiQEz3K5Yk=,iv:4Te3vm4Y0mPCi0m/7yMjB28deRi+K4Kh6gPJtp8eZ1g=,tag:K2Wb3snhZ+JfF7ieU/1Jdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
