apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:WUx5kdsZBgljuA==,iv:J1lialWaE/MoEFdTio5niekOh0A67i3hekDogWD4vKw=,tag:RFb602YKRcjGjo9W1zE2ZA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:O4ykixG/Fumwow==,iv:1zz4xzP7kg3E/WdXqWVZJprlX4+b8QeGV07JRe5OABM=,tag:qWvk/Cm6Ar5EMCza1VDngw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BnPaKuscEwljsr44H1KUhuZxVGY=,iv:GQ/MwYWLjI6oezUAIKMJbtfTkDHo8rZh9m2eRWtLjxQ=,tag:ZjSYzIFc7QOVU69g0lknzA==,type:str]
sops:
    age:
        - recipient: age17j86p3pj260t0g03xv5wsq6u8y422m634pd5j4tdv92z0hf2hc4s4gyt6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYmIwYVpkYzhFWXdxNVBQ
            Q2gzbzJtTUc4WmNXOGJiK01rTWMyNjlsbG1zCjcwTy9DeXRjWEpLQWUvNW5nMVlj
            UlRqMjBIVjMwU29HT05sMHByUkNnak0KLS0tIGlPRFZ0YkgrdjBTN1pqakpVbC9j
            c3EzQzlUNmI3Qyt2OTllUTFqMkdYeU0KjhvP2/lrSTsxezc1TiNnZs1kI2Zem1PG
            9xFIbmzJRF00vhTyWWaOb+lW1r1oMigfs8ub/L+T1IMnlvO21+u+5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T17:27:13Z"
    mac: ENC[AES256_GCM,data:mikbtNo3OHfSdBiuXA0NaUwIQ76/sVg0WSYfvRkZsczBjA7+J0yFe6yfOolre0ZKoGm5fs8JjWHAig+WdtFW4222hdMwAhkbRX+MNN48MHSLg7TI8ROpkcjHHuu7rZivp9KIemgrWjR7q8+4QO6nBAOnBMjeXXPQixwdr3E8lqg=,iv:E2+ZYoUt3lH98l/DmbcrauqIaTyKNQ5UKXPI/gCInJg=,tag:zbVJLjVS0XUqw9RWa4twEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
