name: Test Secret

on:
  push:
    branches:
      - test-secretes
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.KUBECONFIG_B64 }}" ]; then
            echo "Secret is NOT set"
            exit 1
          else
            echo "Secret is set"
          fi
